source/Conference/Conference.Web.Public/Controllers/ConferenceController.cs
// ==============================================================================================================
// Microsoft patterns & practices
// CQRS Journey project
// ==============================================================================================================
// ©2012 Microsoft. All rights reserved. Certain content used with permission from contributors
// http://go.microsoft.com/fwlink/p/?LinkID=258575
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance 
// with the License. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
// Unless required by applicable law or agreed to in writing, software distributed under the License is 
// distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. 
// See the License for the specific language governing permissions and limitations under the License.
// ==============================================================================================================

namespace Conference.Web.Public.Controllers
{
    using System;
    using System.Web.Mvc;
    using Registration.ReadModel;

    public class ConferenceController : Controller
    {
        private readonly IConferenceDao dao;

        public ConferenceController(IConferenceDao dao)
        {
            this.dao = dao;
        }

        public ActionResult Display(string conferenceCode)
        {
            var conference = this.dao.GetConferenceDetails(conferenceCode);

            // Reply with 404 if not found?
            //if (conference == null)

            return View(conference);
        }
    }
}

source/Conference/Conference.Web.Public/Controllers/OrderController.cs
// ==============================================================================================================
// Microsoft patterns & practices
// CQRS Journey project
// ==============================================================================================================
// ©2012 Microsoft. All rights reserved. Certain content used with permission from contributors
// http://go.microsoft.com/fwlink/p/?LinkID=258575
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance 
// with the License. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
// Unless required by applicable law or agreed to in writing, software distributed under the License is 
// distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. 
// See the License for the specific language governing permissions and limitations under the License.
// ==============================================================================================================

namespace Conference.Web.Public.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web.Mvc;
    using AutoMapper;
    using Infrastructure.Messaging;
    using Registration.Commands;
    using Registration.ReadModel;

    public class OrderController : ConferenceTenantController
    {
        private readonly IOrderDao orderDao;
        private readonly ICommandBus bus;

        static OrderController()
        {
            Mapper.CreateMap<OrderSeat, AssignSeat>();
        }

        public OrderController(IConferenceDao conferenceDao, IOrderDao orderDao, ICommandBus bus)
            : base(conferenceDao)
        {
            this.orderDao = orderDao;
            this.bus = bus;
        }

        [HttpGet]
        public ActionResult Display(Guid orderId)
        {
            var order = orderDao.FindPricedOrder(orderId);
            if (order == null)
                return RedirectToAction("Find", new { conferenceCode = this.ConferenceCode });

            return View(order);
        }

        [HttpGet]
        [OutputCache(Duration = 0, NoStore = true)]
        public RedirectToRouteResult AssignSeatsForOrder(Guid orderId)
        {
            var order = orderDao.FindPricedOrder(orderId);
            if (order == null || !order.AssignmentsId.HasValue)
            {
                return RedirectToAction("Display", new { orderId });
            }

            return RedirectToAction("AssignSeats", new { assignmentsId = order.AssignmentsId });
        }

        [HttpGet]
        [OutputCache(Duration = 0, NoStore = true)]
        public ActionResult AssignSeats(Guid assignmentsId)
        {
            var assignments = this.orderDao.FindOrderSeats(assignmentsId);
            if (assignments == null)
                return RedirectToAction("Find", new { conferenceCode = this.ConferenceCode });

            return View(assignments);
        }

        [HttpPost]
        public ActionResult AssignSeats(Guid assignmentsId, List<OrderSeat> seats)
        {
            var saved = this.orderDao.FindOrderSeats(assignmentsId);
            if (saved == null)
                return RedirectToAction("Find", new { conferenceCode = this.ConferenceCode });

            var pairs = seats
                // If a seat is null, it's because it's an invalid null entry 
                // in the list of seats, so we ignore it.
                .Where(seat => seat != null)
                .Select(seat => new { Saved = saved.Seats.FirstOrDefault(x => x.Position == seat.Position), New = seat })
                // Ignore posted seats that we don't have saved already: pair.Saved == null
                // This may be because the client sent mangled or incorrect data so we couldn't 
                // find a matching saved seat.
                .Where(pair => pair.Saved != null)
                // Only process those that have an email (i.e. they are or were assigned)
                .Where(pair => pair.Saved.Attendee.Email != null || pair.New.Attendee.Email != null)
                .ToList();

            // NOTE: in the read model, we care about the OrderId, 
            // but the write side uses a different aggregate root id for the seat 
            // assignments, so we pass that on when we issue commands.

            var unassigned = pairs
                .Where(x => !string.IsNullOrWhiteSpace(x.Saved.Attendee.Email) && string.IsNullOrWhiteSpace(x.New.Attendee.Email))
                .Select(x => (ICommand)new UnassignSeat { SeatAssignmentsId = saved.AssignmentsId, Position = x.Saved.Position });

            var changed = pairs
                .Where(x => x.Saved.Attendee != x.New.Attendee && x.New.Attendee.Email != null)
                .Select(x => (ICommand)Mapper.Map(x.New, new AssignSeat { SeatAssignmentsId = saved.AssignmentsId }));

            var commands = unassigned.Union(changed).ToList();
            if (commands.Count > 0)
            {
                this.bus.Send(commands);
            }

            return RedirectToAction("Display", new { orderId = saved.OrderId });
        }

        [HttpGet]
        public ActionResult Find()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Find(string email, string accessCode)
        {
            var orderId = orderDao.LocateOrder(email, accessCode);

            if (!orderId.HasValue)
            {
                // TODO: 404?
                return RedirectToAction("Find", new { conferenceCode = this.ConferenceCode });
            }

            return RedirectToAction("Display", new { conferenceCode = this.ConferenceCode, orderId = orderId.Value });
        }
    }
}

source/Conference/Conference.Web.Public/Controllers/RegistrationController.cs
// ==============================================================================================================
// Microsoft patterns & practices
// CQRS Journey project
// ==============================================================================================================
// ©2012 Microsoft. All rights reserved. Certain content used with permission from contributors
// http://go.microsoft.com/fwlink/p/?LinkID=258575
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance 
// with the License. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
// Unless required by applicable law or agreed to in writing, software distributed under the License is 
// distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. 
// See the License for the specific language governing permissions and limitations under the License.
// ==============================================================================================================

namespace Conference.Web.Public.Controllers
{
    using System;
    using System.Linq;
    using System.Threading.Tasks;
    using System.Web.Mvc;
    using Conference.Web.Public.Models;
    using Infrastructure.Messaging;
    using Infrastructure.Tasks;
    using Infrastructure.Utils;
    using Payments.Contracts.Commands;
    using Registration.Commands;
    using Registration.ReadModel;

    public class RegistrationController : ConferenceTenantController
    {
        public const string ThirdPartyProcessorPayment = "thirdParty";
        public const string InvoicePayment = "invoice";
        private static readonly TimeSpan DraftOrderWaitTimeout = TimeSpan.FromSeconds(5);
        private static readonly TimeSpan DraftOrderPollInterval = TimeSpan.FromMilliseconds(750);
        private static readonly TimeSpan PricedOrderWaitTimeout = TimeSpan.FromSeconds(5);
        private static readonly TimeSpan PricedOrderPollInterval = TimeSpan.FromMilliseconds(750);

        private readonly ICommandBus commandBus;
        private readonly IOrderDao orderDao;

        public RegistrationController(ICommandBus commandBus, IOrderDao orderDao, IConferenceDao conferenceDao)
            : base(conferenceDao)
        {
            this.commandBus = commandBus;
            this.orderDao = orderDao;
        }

        [HttpGet]
        [OutputCache(Duration = 0, NoStore = true)]
        public Task<ActionResult> StartRegistration(Guid? orderId = null)
        {
            var viewModelTask = Task.Factory.StartNew(() => this.CreateViewModel());
            if (!orderId.HasValue)
            {
                return viewModelTask
                    .ContinueWith<ActionResult>(t =>
                    {
                        var viewModel = t.Result;
                        viewModel.OrderId = GuidUtil.NewSequentialId();
                        return View(viewModel);
                    });
            }
            else
            {
                return Task.Factory.ContinueWhenAll<ActionResult>(
                    new Task[] { viewModelTask, this.WaitUntilSeatsAreConfirmed(orderId.Value, 0) }, 
                    tasks =>
                    {
                        var viewModel = ((Task<OrderViewModel>)tasks[0]).Result;
                        var order = ((Task<DraftOrder>)tasks[1]).Result;

                        if (order == null)
                        {
                            return View("PricedOrderUnknown");
                        }

                        if (order.State == DraftOrder.States.Confirmed)
                        {
                            return View("ShowCompletedOrder");
                        }

                        if (order.ReservationExpirationDate.HasValue && order.ReservationExpirationDate < DateTime.UtcNow)
                        {
                            return RedirectToAction("ShowExpiredOrder", new { conferenceCode = this.ConferenceAlias.Code, orderId = orderId });
                        }

                        UpdateViewModel(viewModel, order);
                        return View(viewModel);
                    });
            }
        }

        [HttpPost]
        public ActionResult StartRegistration(RegisterToConference command, int orderVersion)
        {
            var existingOrder = orderVersion != 0 ? this.orderDao.FindDraftOrder(command.OrderId) : null;
            var viewModel = this.CreateViewModel();
            if (existingOrder != null)
            {
                UpdateViewModel(viewModel, existingOrder);
            }

            viewModel.OrderId = command.OrderId;

            if (!ModelState.IsValid)
            {
                return View(viewModel);
            }

            // checks that there are still enough available seats, and the seat type IDs submitted are valid.
            ModelState.Clear();
            bool needsExtraValidation = false;
            foreach (var seat in command.Seats)
            {
                var modelItem = viewModel.Items.FirstOrDefault(x => x.SeatType.Id == seat.SeatType);
                if (modelItem != null)
                {
                    if (seat.Quantity > modelItem.MaxSelectionQuantity)
                    {
                        modelItem.PartiallyFulfilled = needsExtraValidation = true;
                        modelItem.OrderItem.ReservedSeats = modelItem.MaxSelectionQuantity;
                    }
                }
                else
                {
                    // seat type no longer exists for conference.
                    needsExtraValidation = true;
                }
            }

            if (needsExtraValidation)
            {
                return View(viewModel);
            }

            command.ConferenceId = this.ConferenceAlias.Id;
            this.commandBus.Send(command);

            return RedirectToAction(
                "SpecifyRegistrantAndPaymentDetails",
                new { conferenceCode = this.ConferenceCode, orderId = command.OrderId, orderVersion = orderVersion });
        }

        [HttpGet]
        [OutputCache(Duration = 0, NoStore = true)]
        public Task<ActionResult> SpecifyRegistrantAndPaymentDetails(Guid orderId, int orderVersion)
        {
            return this.WaitUntilOrderIsPriced(orderId, orderVersion)
            .ContinueWith<ActionResult>(t =>
            {
                var pricedOrder = t.Result;
                if (pricedOrder == null)
                {
                    return View("PricedOrderUnknown");
                }

                if (!pricedOrder.ReservationExpirationDate.HasValue)
                {
                    return View("ShowCompletedOrder");
                }

                if (pricedOrder.ReservationExpirationDate < DateTime.UtcNow)
                {
                    return RedirectToAction("ShowExpiredOrder", new { conferenceCode = this.ConferenceAlias.Code, orderId = orderId });
                }

                return View(
                    new RegistrationViewModel
                    {
                        RegistrantDetails = new AssignRegistrantDetails { OrderId = orderId },
                        Order = pricedOrder
                    });
            });
        }

        [HttpPost]
        public Task<ActionResult> SpecifyRegistrantAndPaymentDetails(AssignRegistrantDetails command, string paymentType, int orderVersion)
        {
            var orderId = command.OrderId;

            if (!ModelState.IsValid)
            {
                return SpecifyRegistrantAndPaymentDetails(orderId, orderVersion);
            }

            this.commandBus.Send(command);

            return this.StartPayment(orderId, paymentType, orderVersion);
        }

        [HttpPost]
        public Task<ActionResult> StartPayment(Guid orderId, string paymentType, int orderVersion)
        {
            return this.WaitUntilSeatsAreConfirmed(orderId, orderVersion)
                .ContinueWith<ActionResult>(t =>
                {
                    var order = t.Result;
                    if (order == null)
                    {
                        return View("ReservationUnknown");
                    }

                    if (order.State == DraftOrder.States.PartiallyReserved)
                    {
                        //TODO: have a clear message in the UI saying there was a problem and he actually didn't get all the seats.
                        // This happened as a result the seats availability being eventually but not fully consistent when
                        // starting the reservation. It is very uncommon to reach this step, but could happen under heavy
                        // load, and when competing for the last remaining seats of the conference.
                        return this.RedirectToAction("StartRegistration", new { conferenceCode = this.ConferenceCode, orderId, orderVersion = order.OrderVersion });
                    }

                    if (order.State == DraftOrder.States.Confirmed)
                    {
                        return View("ShowCompletedOrder");
                    }

                    if (order.ReservationExpirationDate.HasValue && order.ReservationExpirationDate < DateTime.UtcNow)
                    {
                        return RedirectToAction("ShowExpiredOrder", new { conferenceCode = this.ConferenceAlias.Code, orderId = orderId });
                    }

                    var pricedOrder = this.orderDao.FindPricedOrder(orderId);
                    if (pricedOrder.IsFreeOfCharge)
                    {
                        return CompleteRegistrationWithoutPayment(orderId);
                    }


source/Conference/Conference.Web.Public/Views/Conference/Display.cshtml
@model Registration.ReadModel.ConferenceDetails
@{
    ViewBag.Title = Model.Name;
}

@ConferenceHelpers.ConferenceTitle(Model.Name, Model.Tagline)

<div class="page__content">
    <div class="page__wrapper content-main">
        <div class="content-main__wrapper">
            <div class="content-main__main">
                <div class="content-main__header"></div>
                <a class="tile" href="#">
                    <span class="tile__imgs tile-slide">
						<img class="tile__img" src="@Url.Content("~/Content/tmp/pic_.jpg")" alt="" style="width: 250px;">
						<img class="tile__img" src="@Url.Content("~/Content/tmp/pic_1.jpg")" alt="" style="width: 250px;">
						<img class="tile__img" src="@Url.Content("~/Content/tmp/pic_2.jpg")" alt="" style="width: 250px;">
					</span>
                    <span class="tile__header">Speakers</span>
                </a>
                <a class="tile tile_narrow" href="#">
                    <span class="tile__img-container">
                        <img src="@Url.Content("~/Content/Conference/date.png")" alt="About event">
                    </span>
                    <span class="tile__header">About event</span>
                </a>
                <a class="tile" href="#">
					<span class="tile__imgs tile-slide">
						<img class="tile__img" src="@Url.Content("~/Content/Conference/sessions.png")" alt="" style="z-index: 10;">
						<span style="display: none;">
							<span class="tile__topic">Get the .NET Framework 1.1 – MSDN
								Explore Windows, Web, Cloud
							</span>
							<span class="tile__span">11:00 am – 12:00 am</span>
						</span>
					</span>
                    <span class="tile__header">Sessions</span>
                </a>
                <a class="tile tile_narrow" href="#">
					<span class="tile__imgs tile-slide">
						<img class="tile__img" src="@Url.Content("~/Content/Conference/destination.png")" alt="" style="z-index: 10;">
						<img class="tile__img" src="@Url.Content("~/Content/tmp/pic_1.jpg")" alt="">
						<img class="tile__img" src="@Url.Content("~/Content/tmp/pic_2.jpg")" alt="">
					</span>
                    <span class="tile__header">Destination</span>
                </a>
                <a class="tile" href="#">
                    <span class="tile__topic">Automating your build process with perforated cards
                    </span>
                    <span class="tile__span">11:00 am – 12:00 am</span>
                    <span class="tile__header">Event topics <span class="tile__nav"><span
                            class="tile__nav-item tile__nav-item_active"><i></i></span><span
                            class="tile__nav-item"><i></i></span><span
                            class="tile__nav-item"><i></i></span><span
                            class="tile__nav-item"><i></i></span></span></span>
                </a>
                <a class="tile tile_narrow" href="#">
					<span class="tile__imgs tile-slide">
						<img class="tile__img" src="@Url.Content("~/Content/Conference/organizers.png")" alt="" style="z-index: 10;">
						<img class="tile__img" src="@Url.Content("~/Content/tmp/pic_1.jpg")" alt="">
						<img class="tile__img" src="@Url.Content("~/Content/tmp/pic_2.jpg")" alt="">
					</span>
                    <span class="tile__header">Organizers</span>
                </a>
            </div>
        </div>
        <div class="content-main__aside">
            <div class="content-main__header"></div>
            <a class="tile tile_register" href="@Url.Action("StartRegistration", "Registration")">
                <span class="tile__header">Register <i></i></span>
@*                <span class="tile__note">Only <strong>50 seats available</strong>!<br>
                    Register by March 25 //TODO
                </span>*@
            </a>
        </div>
        <div class="content-main__extra">
            <div class="content-main__header">Media</div>
            <div class="content-main__extra-right">
                <a class="tile tile_small" href="#">
                    <img src="@Url.Content("~/Content/Conference/plus.png")" alt="">
                    <span class="tile__header">Add to my calendar</span>
                </a>
            </div>
            <div class="content-main__extra-left">
                <a class="tile" href="#">
                    <span class="tile__img-container">
                        <img src="@Url.Content("~/Content/Conference/sponsors.png")" alt="">
                    </span>
                    <span class="tile__header">Sponsor</span>
                </a>
                <a class="tile" href="#">
                    <span class="tile__img-container">
                        <img src="@Url.Content("~/Content/Conference/press.png")" alt="">
                    </span>
                    <span class="tile__header">Press</span>
                </a>
                @{ var twitter = Model.TwitterSearch ?? "#cqrsjourney"; }
                <a class="tile tile_twitter" href="https://twitter.com/#!/search/@Url.Encode(twitter)" target="_search">
                    <span class="tile__header">Twitter</span>
                    <span id="tweets" class="tile-slide" data-search="@Url.Encode(twitter)">
                  @*    <span class="tile__tweet">
							<span class="tile__nick"><span class="tile__time">4h ago</span>@gmelnik</span>RT @jasondentler: The work coming out of @mspnp for CQRS is really useful. Nice 180 from the "enterprisey" app block days.
						</span>
						<span class="tile__tweet">
							<span class="tile__nick"><span class="tile__time">4h ago</span>@ashic</span>RT @jasondentler: The work coming out of @mspnp for CQRS is really useful. Nice 180 from the "enterprisey" app block days.
						</span>
						<span class="tile__tweet">
							<span class="tile__nick"><span class="tile__time">4h ago</span>@jasondentler</span>The work coming out of @mspnp for CQRS is really useful. Nice 180 from the "enterprisey" app block days.
						</span>*@
					</span>
                </a>
            </div>
        </div>
        <div class="g-clear"></div>
        <div class="content-main__time-n-place time-n-place">
            <div class="time-n-place__date">@Model.StartDate.ToString("MMM d")</div>
            <div class="time-n-place__time">@Model.StartDate.ToString("hh:mm tt")</div>
            <div class="time-n-place__place">@Model.Location</div>
        </div>

    </div>
</div>
<div class="page__likes page__wrapper">
    <div class="page__wrapper likes">
        <a class="likes__link likes__link_facebook" href="#"></a><a class="likes__link likes__link_mail" href="#"></a><a class="likes__link likes__link_twitter" href="#"></a>
    </div>
</div>



@section Navigation
{
    <a class="quick__login" href="@Url.Action("Find", "Order")">Locate Registration</a>
}

@section Scripts
{
<script src="//ajax.aspnetcdn.com/ajax/jquery.cycle/2.99/jquery.cycle.all.min.js" type="text/javascript"></script>
<script type="text/javascript" src="@Url.Content("~/Scripts/main.js")"></script>
}